// <auto-generated />
using GHEBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GHEBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708201453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GHEBackend.Models.Declaration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BiddingProcess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractNegotiation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instances")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LineManager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PublicOfficial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReceivedGiven")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Submitted")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Substantiation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TeamMemberNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Declarations");

                    b.HasData(
                        new
                        {
                            Id = "GHE-2024-0047",
                            Approver = "Sipho Nkosi",
                            BiddingProcess = "No",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "John Smith",
                            Counterparty = "Tsogo Sun Hotels",
                            Date = "2024-11-10",
                            Department = "Marketing",
                            Description = "Corporate dinner for key partners at Sandton Sun",
                            Employee = "Nomvula Dlamini",
                            From = "Supplier",
                            Instances = "2",
                            LineManager = "Sipho Nkosi",
                            Occasion = "Relationship Maintenance",
                            Position = "Senior Brand Manager",
                            Priority = "High",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "Client – Strategic Partner",
                            Status = "Pending",
                            Submitted = "2024-11-12",
                            Team = "Brand & Communications",
                            TeamMemberNumber = "HB-204478",
                            Type = "Hospitality",
                            Value = 8500m
                        },
                        new
                        {
                            Id = "GHE-2024-0046",
                            Approver = "Sipho Nkosi",
                            BiddingProcess = "No",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Jane Dube",
                            Counterparty = "Makro",
                            Date = "2024-11-08",
                            Department = "Sales",
                            Description = "End-of-year gift basket received from supplier",
                            Employee = "Thabo Mokoena",
                            From = "Supplier",
                            Instances = "1",
                            LineManager = "Lindiwe Zulu",
                            Occasion = "Festive",
                            Position = "Sales Executive",
                            Priority = "Low",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "Supplier – Regular",
                            Status = "Approved",
                            Submitted = "2024-11-10",
                            Team = "Enterprise Sales",
                            TeamMemberNumber = "HB-187234",
                            Type = "Gift",
                            Value = 1200m
                        },
                        new
                        {
                            Id = "GHE-2024-0045",
                            Approver = "Lindiwe Zulu",
                            BiddingProcess = "Yes",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Ahmed Al-Rashid",
                            Counterparty = "Emirates Airline",
                            Date = "2024-11-05",
                            Department = "Operations",
                            Description = "Business class flights and lounge access for conference",
                            Employee = "Ayanda Khumalo",
                            From = "Customer",
                            Instances = "3",
                            LineManager = "Sipho Nkosi",
                            Occasion = "Other",
                            Position = "Operations Manager",
                            Priority = "High",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "Counterparty – Technology",
                            Status = "Escalated",
                            Submitted = "2024-11-08",
                            Team = "Operations",
                            TeamMemberNumber = "HB-219033",
                            Type = "Entertainment",
                            Value = 34000m
                        },
                        new
                        {
                            Id = "GHE-2024-0044",
                            Approver = "Sipho Nkosi",
                            BiddingProcess = "No",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Mark Johnson",
                            Counterparty = "La Colombe Restaurant",
                            Date = "2024-11-04",
                            Department = "Finance",
                            Description = "Lunch meeting with audit consultants",
                            Employee = "Pieter van der Berg",
                            From = "Customer",
                            Instances = "1",
                            LineManager = "Lindiwe Zulu",
                            Occasion = "Relationship Maintenance",
                            Position = "Finance Analyst",
                            Priority = "Medium",
                            PublicOfficial = "No",
                            ReceivedGiven = "Given",
                            Relationship = "Service Provider – Annual",
                            Status = "Declined",
                            Submitted = "2024-11-06",
                            Team = "Financial Reporting",
                            TeamMemberNumber = "HB-156902",
                            Type = "Hospitality",
                            Value = 3200m
                        },
                        new
                        {
                            Id = "GHE-2024-0043",
                            Approver = "Lindiwe Zulu",
                            BiddingProcess = "No",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Thandi Molefe",
                            Counterparty = "Woolworths",
                            Date = "2024-11-02",
                            Department = "HR",
                            Description = "Festive season hamper from staffing agency",
                            Employee = "Zanele Sithole",
                            From = "Supplier",
                            Instances = "1",
                            LineManager = "Sipho Nkosi",
                            Occasion = "Festive",
                            Position = "HR Generalist",
                            Priority = "Low",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "Supplier – Staffing",
                            Status = "Approved",
                            Submitted = "2024-11-04",
                            Team = "People & Culture",
                            TeamMemberNumber = "HB-198741",
                            Type = "Gift",
                            Value = 650m
                        },
                        new
                        {
                            Id = "GHE-2024-0042",
                            Approver = "Sipho Nkosi",
                            BiddingProcess = "Yes",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Riaan Botha",
                            Counterparty = "Sun International",
                            Date = "2024-10-31",
                            Department = "IT",
                            Description = "Golf day and networking event hosted by Sun International",
                            Employee = "Bongani Cele",
                            From = "Supplier",
                            Instances = "2",
                            LineManager = "Lindiwe Zulu",
                            Occasion = "Relationship Maintenance",
                            Position = "IT Systems Lead",
                            Priority = "Medium",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "Counterparty – IT Solutions",
                            Status = "Pending",
                            Submitted = "2024-11-02",
                            Team = "Technology",
                            TeamMemberNumber = "HB-234512",
                            Type = "Entertainment",
                            Value = 12800m
                        },
                        new
                        {
                            Id = "GHE-2024-0041",
                            Approver = "Lindiwe Zulu",
                            BiddingProcess = "N/A",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Priya Naidoo",
                            Counterparty = "Edgars",
                            Date = "2024-10-28",
                            Department = "Legal",
                            Description = "Clothing voucher received at legal conference",
                            Employee = "Fatima Ismail",
                            From = "Customer",
                            Instances = "1",
                            LineManager = "Sipho Nkosi",
                            Occasion = "Other",
                            Position = "Legal Counsel",
                            Priority = "Medium",
                            PublicOfficial = "No",
                            ReceivedGiven = "Received",
                            Relationship = "External – Industry Event",
                            Status = "Info Requested",
                            Submitted = "2024-10-30",
                            Team = "Legal & Compliance",
                            TeamMemberNumber = "HB-167823",
                            Type = "Gift",
                            Value = 890m
                        },
                        new
                        {
                            Id = "GHE-2024-0040",
                            Approver = "Sipho Nkosi",
                            BiddingProcess = "No",
                            Company = "Hollywoodbets Group",
                            ContactPerson = "Lebo Mahlangu",
                            Counterparty = "Radisson Blu",
                            Date = "2024-10-25",
                            Department = "Marketing",
                            Description = "Team dinner for campaign launch celebration",
                            Employee = "Siphamandla Ndlovu",
                            From = "Team Member",
                            Instances = "1",
                            LineManager = "Lindiwe Zulu",
                            Occasion = "Milestone",
                            Position = "Brand Strategist",
                            Priority = "Low",
                            PublicOfficial = "No",
                            ReceivedGiven = "Given",
                            Relationship = "Internal – Team Event",
                            Status = "Draft",
                            Submitted = "2024-10-28",
                            Team = "Brand & Communications",
                            TeamMemberNumber = "HB-244001",
                            Type = "Hospitality",
                            Value = 5600m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
