-- 0006_numeric_keys: TEXT primary/foreign keys -> native BIGINT identity.
--
-- Goal doc "Identifier Strategy" (development-stage simplification): the
-- normalized PostgreSQL schema is the first production baseline. Disposable
-- development/test databases are reset and reseeded; no legacy-ID
-- preservation mapping is retained. This migration is still written to apply
-- cleanly to an empty OR a populated 0005 database: mappings are
-- deterministic (row_number over created/ordering columns) and unmapped
-- non-null references fail loudly (section D) instead of silently nulling.
--
-- Deliberate exceptions (public/legacy identifiers, not internal keys):
--   * Declaration.id (GHE-YYYY-NNNNNN) stays the public text reference and
--     the physical PK; a new internal declarationPk carries all child FKs.
--   * SystemConfig.id ("default") and ApprovalOption.id ("opt-*"/"ao-*")
--     stay text: singleton/code-list rows outside the numeric-key scope.
--   * UserRole/AppRole, OrganizationSetting, Ref* tables and
--     UploadedFile.declarationId were retired in 0005, so no numeric
--     migration exists for them.
--
-- NOTE on DDL style: new keys use BIGINT GENERATED BY DEFAULT AS IDENTITY
-- per the plan. The Prisma schema expresses the same keys with
-- @default(autoincrement()) (client-compatible); do not run
-- `prisma migrate dev` against production — migrations are hand-owned.

-- ══ A. Drop dependent read models (recreated in section F) ═══════════════
DROP VIEW IF EXISTS "v_declaration_status_summary";
DROP VIEW IF EXISTS "v_declarations_monthly";
DROP VIEW IF EXISTS "v_declaration_type_breakdown";
DROP VIEW IF EXISTS "v_workflow_current_step";
DROP VIEW IF EXISTS "v_workflow_step_sla";
DROP VIEW IF EXISTS "v_counterparty_concentration";
DROP VIEW IF EXISTS "v_high_value_declarations";

-- Scoped-identity partial index (recreated on BIGINT at the end).
DROP INDEX IF EXISTS "Counterparty_name_org_unique";

-- ══ B. Drop legacy constraints that reference columns being replaced ══════
-- Primary keys on replaced TEXT id columns.
ALTER TABLE "Organization" DROP CONSTRAINT IF EXISTS "Organization_pkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_pkey";
ALTER TABLE "Department" DROP CONSTRAINT IF EXISTS "Department_pkey";
ALTER TABLE "Team" DROP CONSTRAINT IF EXISTS "Team_pkey";
ALTER TABLE "Counterparty" DROP CONSTRAINT IF EXISTS "Counterparty_pkey";
ALTER TABLE "CounterpartyContact" DROP CONSTRAINT IF EXISTS "CounterpartyContact_pkey";
ALTER TABLE "UploadedFile" DROP CONSTRAINT IF EXISTS "UploadedFile_pkey";
ALTER TABLE "WorkflowRule" DROP CONSTRAINT IF EXISTS "WorkflowRule_pkey";
ALTER TABLE "WorkflowRuleStep" DROP CONSTRAINT IF EXISTS "WorkflowRuleStep_pkey";
ALTER TABLE "DeclarationSnapshot" DROP CONSTRAINT IF EXISTS "DeclarationSnapshot_pkey";
ALTER TABLE "DeclarationDetail" DROP CONSTRAINT IF EXISTS "DeclarationDetail_pkey";
ALTER TABLE "DeclarationFile" DROP CONSTRAINT IF EXISTS "DeclarationFile_pkey";
ALTER TABLE "WorkflowInstance" DROP CONSTRAINT IF EXISTS "WorkflowInstance_pkey";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_pkey";

-- Legacy foreign keys (auto-named inline REFERENCES plus explicit names).
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_organizationId_fkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_managerId_fkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_departmentId_fkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_teamId_fkey";
ALTER TABLE "Declaration" DROP CONSTRAINT IF EXISTS "Declaration_organizationId_fkey";
ALTER TABLE "Declaration" DROP CONSTRAINT IF EXISTS "Declaration_declarerUserId_fkey";
ALTER TABLE "Declaration" DROP CONSTRAINT IF EXISTS "Declaration_currentApproverUserId_fkey";
ALTER TABLE "Declaration" DROP CONSTRAINT IF EXISTS "Declaration_counterpartyId_fkey";
ALTER TABLE "Department" DROP CONSTRAINT IF EXISTS "Department_organizationId_fkey";
ALTER TABLE "Team" DROP CONSTRAINT IF EXISTS "Team_departmentId_fkey";
ALTER TABLE "Counterparty" DROP CONSTRAINT IF EXISTS "Counterparty_organizationId_fkey";
ALTER TABLE "CounterpartyContact" DROP CONSTRAINT IF EXISTS "CounterpartyContact_counterpartyId_fkey";
ALTER TABLE "DeclarationSnapshot" DROP CONSTRAINT IF EXISTS "DeclarationSnapshot_declarationId_fkey";
ALTER TABLE "DeclarationDetail" DROP CONSTRAINT IF EXISTS "DeclarationDetail_declarationId_fkey";
ALTER TABLE "DeclarationFile" DROP CONSTRAINT IF EXISTS "DeclarationFile_declarationId_fkey";
ALTER TABLE "DeclarationFile" DROP CONSTRAINT IF EXISTS "DeclarationFile_fileId_fkey";
ALTER TABLE "WorkflowRule" DROP CONSTRAINT IF EXISTS "WorkflowRule_organizationId_fkey";
ALTER TABLE "WorkflowRuleStep" DROP CONSTRAINT IF EXISTS "WorkflowRuleStep_ruleId_fkey";
ALTER TABLE "WorkflowInstance" DROP CONSTRAINT IF EXISTS "WorkflowInstance_declaration_fk";
ALTER TABLE "WorkflowInstance" DROP CONSTRAINT IF EXISTS "WorkflowInstance_ruleId_fk";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_instanceId_fkey";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_declarationId_fkey";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_assigneeId_fkey";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_decidedById_fkey";
ALTER TABLE "UploadedFile" DROP CONSTRAINT IF EXISTS "UploadedFile_declaration_fk";

-- Legacy unique constraints on replaced columns.
ALTER TABLE "Department" DROP CONSTRAINT IF EXISTS "Department_organizationId_name_key";
ALTER TABLE "Team" DROP CONSTRAINT IF EXISTS "Team_departmentId_name_key";
ALTER TABLE "Counterparty" DROP CONSTRAINT IF EXISTS "Counterparty_name_organizationId_key";
ALTER TABLE "WorkflowRuleStep" DROP CONSTRAINT IF EXISTS "WorkflowRuleStep_ruleId_order_key";
ALTER TABLE "DeclarationSnapshot" DROP CONSTRAINT IF EXISTS "DeclarationSnapshot_declarationId_key";
ALTER TABLE "DeclarationDetail" DROP CONSTRAINT IF EXISTS "DeclarationDetail_declarationId_key";
ALTER TABLE "DeclarationFile" DROP CONSTRAINT IF EXISTS "DeclarationFile_fileId_key";
ALTER TABLE "WorkflowInstanceStep" DROP CONSTRAINT IF EXISTS "WorkflowInstanceStep_instanceId_stepOrder_key";

-- ══ C1. New BIGINT identity PK columns, deterministically populated ═══════
ALTER TABLE "Organization" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "Organization")
UPDATE "Organization" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"Organization"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "Organization"), 0));

ALTER TABLE "User" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "User")
UPDATE "User" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"User"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "User"), 0));

ALTER TABLE "Department" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "Department")
UPDATE "Department" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"Department"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "Department"), 0));

ALTER TABLE "Team" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "Team")
UPDATE "Team" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"Team"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "Team"), 0));

ALTER TABLE "Counterparty" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "Counterparty")
UPDATE "Counterparty" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"Counterparty"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "Counterparty"), 0));

ALTER TABLE "CounterpartyContact" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "CounterpartyContact")
UPDATE "CounterpartyContact" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"CounterpartyContact"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "CounterpartyContact"), 0));

ALTER TABLE "UploadedFile" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "uploadedAt", "id") AS rn FROM "UploadedFile")
UPDATE "UploadedFile" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"UploadedFile"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "UploadedFile"), 0));

ALTER TABLE "WorkflowRule" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "WorkflowRule")
UPDATE "WorkflowRule" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"WorkflowRule"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "WorkflowRule"), 0));

ALTER TABLE "WorkflowRuleStep" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "ruleId", "order", "id") AS rn FROM "WorkflowRuleStep")
UPDATE "WorkflowRuleStep" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"WorkflowRuleStep"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "WorkflowRuleStep"), 0));

ALTER TABLE "DeclarationSnapshot" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "capturedAt", "declarationId") AS rn FROM "DeclarationSnapshot")
UPDATE "DeclarationSnapshot" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"DeclarationSnapshot"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "DeclarationSnapshot"), 0));

ALTER TABLE "DeclarationDetail" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "declarationId") AS rn FROM "DeclarationDetail")
UPDATE "DeclarationDetail" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"DeclarationDetail"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "DeclarationDetail"), 0));

ALTER TABLE "DeclarationFile" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "DeclarationFile")
UPDATE "DeclarationFile" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"DeclarationFile"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "DeclarationFile"), 0));

ALTER TABLE "WorkflowInstanceStep" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "WorkflowInstanceStep")
UPDATE "WorkflowInstanceStep" o SET "id_new" = m.rn FROM m WHERE o."id" = m."id";
SELECT setval(pg_get_serial_sequence('"WorkflowInstanceStep"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "WorkflowInstanceStep"), 0));

-- Declaration internal numeric key (public text id is untouched).
ALTER TABLE "Declaration" ADD COLUMN "declarationPk" BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH m AS (SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "Declaration")
UPDATE "Declaration" d SET "declarationPk" = m.rn FROM m WHERE d."id" = m."id";
SELECT setval(pg_get_serial_sequence('"Declaration"', 'declarationPk'), COALESCE((SELECT MAX("declarationPk") FROM "Declaration"), 0));
ALTER TABLE "Declaration" ADD CONSTRAINT "Declaration_declarationPk_key" UNIQUE ("declarationPk");

-- WorkflowInstance: new numeric PK plus numeric declaration reference.
ALTER TABLE "WorkflowInstance" ADD COLUMN "id_new" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "WorkflowInstance" ADD COLUMN "declarationPk_new" BIGINT;
WITH m AS (SELECT "declarationId", row_number() OVER (ORDER BY "createdAt", "declarationId") AS rn FROM "WorkflowInstance")
UPDATE "WorkflowInstance" w SET "id_new" = m.rn FROM m WHERE w."declarationId" = m."declarationId";
UPDATE "WorkflowInstance" w SET "declarationPk_new" = d."declarationPk" FROM "Declaration" d WHERE d."id" = w."declarationId";
SELECT setval(pg_get_serial_sequence('"WorkflowInstance"', 'id_new'), COALESCE((SELECT MAX("id_new") FROM "WorkflowInstance"), 0));

-- ══ C2. BIGINT FK shadow columns, populated through the mapped parents ════
ALTER TABLE "User" ADD COLUMN "organizationId_new" BIGINT;
ALTER TABLE "User" ADD COLUMN "managerId_new" BIGINT;
ALTER TABLE "User" ADD COLUMN "departmentId_new" BIGINT;
ALTER TABLE "User" ADD COLUMN "teamId_new" BIGINT;
UPDATE "User" u SET "organizationId_new" = o."id_new" FROM "Organization" o WHERE o."id" = u."organizationId";
UPDATE "User" u SET "managerId_new" = m."id_new" FROM "User" m WHERE m."id" = u."managerId";
UPDATE "User" u SET "departmentId_new" = d."id_new" FROM "Department" d WHERE d."id" = u."departmentId";
UPDATE "User" u SET "teamId_new" = t."id_new" FROM "Team" t WHERE t."id" = u."teamId";

ALTER TABLE "Department" ADD COLUMN "organizationId_new" BIGINT;
UPDATE "Department" d SET "organizationId_new" = o."id_new" FROM "Organization" o WHERE o."id" = d."organizationId";

ALTER TABLE "Team" ADD COLUMN "departmentId_new" BIGINT;
UPDATE "Team" t SET "departmentId_new" = d."id_new" FROM "Department" d WHERE d."id" = t."departmentId";

ALTER TABLE "Counterparty" ADD COLUMN "organizationId_new" BIGINT;
UPDATE "Counterparty" c SET "organizationId_new" = o."id_new" FROM "Organization" o WHERE o."id" = c."organizationId";

ALTER TABLE "CounterpartyContact" ADD COLUMN "counterpartyId_new" BIGINT;
UPDATE "CounterpartyContact" cc SET "counterpartyId_new" = c."id_new" FROM "Counterparty" c WHERE c."id" = cc."counterpartyId";

ALTER TABLE "Declaration" ADD COLUMN "organizationId_new" BIGINT;
ALTER TABLE "Declaration" ADD COLUMN "declarerUserId_new" BIGINT;
ALTER TABLE "Declaration" ADD COLUMN "currentApproverUserId_new" BIGINT;
ALTER TABLE "Declaration" ADD COLUMN "counterpartyId_new" BIGINT;
UPDATE "Declaration" d SET "organizationId_new" = o."id_new" FROM "Organization" o WHERE o."id" = d."organizationId";
UPDATE "Declaration" d SET "declarerUserId_new" = u."id_new" FROM "User" u WHERE u."id" = d."declarerUserId";
UPDATE "Declaration" d SET "currentApproverUserId_new" = u."id_new" FROM "User" u WHERE u."id" = d."currentApproverUserId";
UPDATE "Declaration" d SET "counterpartyId_new" = c."id_new" FROM "Counterparty" c WHERE c."id" = d."counterpartyId";

ALTER TABLE "DeclarationSnapshot" ADD COLUMN "declarationPk_new" BIGINT;
UPDATE "DeclarationSnapshot" s SET "declarationPk_new" = d."declarationPk" FROM "Declaration" d WHERE d."id" = s."declarationId";

ALTER TABLE "DeclarationDetail" ADD COLUMN "declarationPk_new" BIGINT;
UPDATE "DeclarationDetail" s SET "declarationPk_new" = d."declarationPk" FROM "Declaration" d WHERE d."id" = s."declarationId";

ALTER TABLE "DeclarationFile" ADD COLUMN "declarationPk_new" BIGINT;
ALTER TABLE "DeclarationFile" ADD COLUMN "fileId_new" BIGINT;
UPDATE "DeclarationFile" l SET "declarationPk_new" = d."declarationPk" FROM "Declaration" d WHERE d."id" = l."declarationId";
UPDATE "DeclarationFile" l SET "fileId_new" = f."id_new" FROM "UploadedFile" f WHERE f."id" = l."fileId";

ALTER TABLE "WorkflowRule" ADD COLUMN "organizationId_new" BIGINT;
UPDATE "WorkflowRule" r SET "organizationId_new" = o."id_new" FROM "Organization" o WHERE o."id" = r."organizationId";

ALTER TABLE "WorkflowRuleStep" ADD COLUMN "ruleId_new" BIGINT;
UPDATE "WorkflowRuleStep" s SET "ruleId_new" = r."id_new" FROM "WorkflowRule" r WHERE r."id" = s."ruleId";

ALTER TABLE "WorkflowInstance" ADD COLUMN "ruleId_new" BIGINT;
UPDATE "WorkflowInstance" w SET "ruleId_new" = r."id_new" FROM "WorkflowRule" r WHERE r."id" = w."ruleId";

ALTER TABLE "WorkflowInstanceStep" ADD COLUMN "instanceId_new" BIGINT;
ALTER TABLE "WorkflowInstanceStep" ADD COLUMN "declarationPk_new" BIGINT;
ALTER TABLE "WorkflowInstanceStep" ADD COLUMN "assigneeId_new" BIGINT;
ALTER TABLE "WorkflowInstanceStep" ADD COLUMN "decidedById_new" BIGINT;
UPDATE "WorkflowInstanceStep" s SET "instanceId_new" = w."id_new" FROM "WorkflowInstance" w WHERE w."declarationId" = s."instanceId";
UPDATE "WorkflowInstanceStep" s SET "declarationPk_new" = d."declarationPk" FROM "Declaration" d WHERE d."id" = s."declarationId";
UPDATE "WorkflowInstanceStep" s SET "assigneeId_new" = u."id_new" FROM "User" u WHERE u."id" = s."assigneeId";
UPDATE "WorkflowInstanceStep" s SET "decidedById_new" = u."id_new" FROM "User" u WHERE u."id" = s."decidedById";

-- ══ D. Orphan gate: any non-null legacy reference without a mapped target
-- fails the migration instead of silently nulling a relationship. ══════════
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "User" WHERE "organizationId" IS NOT NULL AND "organizationId_new" IS NULL) THEN RAISE EXCEPTION '0006: User.organizationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "User" WHERE "managerId" IS NOT NULL AND "managerId_new" IS NULL) THEN RAISE EXCEPTION '0006: User.managerId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "User" WHERE "departmentId" IS NOT NULL AND "departmentId_new" IS NULL) THEN RAISE EXCEPTION '0006: User.departmentId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "User" WHERE "teamId" IS NOT NULL AND "teamId_new" IS NULL) THEN RAISE EXCEPTION '0006: User.teamId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Department" WHERE "organizationId_new" IS NULL) THEN RAISE EXCEPTION '0006: Department.organizationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Team" WHERE "departmentId_new" IS NULL) THEN RAISE EXCEPTION '0006: Team.departmentId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Counterparty" WHERE "organizationId" IS NOT NULL AND "organizationId_new" IS NULL) THEN RAISE EXCEPTION '0006: Counterparty.organizationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "CounterpartyContact" WHERE "counterpartyId_new" IS NULL) THEN RAISE EXCEPTION '0006: CounterpartyContact.counterpartyId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Declaration" WHERE "organizationId" IS NOT NULL AND "organizationId_new" IS NULL) THEN RAISE EXCEPTION '0006: Declaration.organizationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Declaration" WHERE "declarerUserId" IS NOT NULL AND "declarerUserId_new" IS NULL) THEN RAISE EXCEPTION '0006: Declaration.declarerUserId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Declaration" WHERE "currentApproverUserId" IS NOT NULL AND "currentApproverUserId_new" IS NULL) THEN RAISE EXCEPTION '0006: Declaration.currentApproverUserId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "Declaration" WHERE "counterpartyId" IS NOT NULL AND "counterpartyId_new" IS NULL) THEN RAISE EXCEPTION '0006: Declaration.counterpartyId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "DeclarationSnapshot" WHERE "declarationPk_new" IS NULL) THEN RAISE EXCEPTION '0006: DeclarationSnapshot.declarationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "DeclarationDetail" WHERE "declarationPk_new" IS NULL) THEN RAISE EXCEPTION '0006: DeclarationDetail.declarationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "DeclarationFile" WHERE "declarationPk_new" IS NULL) THEN RAISE EXCEPTION '0006: DeclarationFile.declarationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "DeclarationFile" WHERE "fileId_new" IS NULL) THEN RAISE EXCEPTION '0006: DeclarationFile.fileId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowRule" WHERE "organizationId" IS NOT NULL AND "organizationId_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowRule.organizationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowRuleStep" WHERE "ruleId_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowRuleStep.ruleId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstance" WHERE "declarationPk_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstance.declarationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstance" WHERE "ruleId" IS NOT NULL AND "ruleId_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstance.ruleId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstanceStep" WHERE "instanceId_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstanceStep.instanceId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstanceStep" WHERE "declarationPk_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstanceStep.declarationId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstanceStep" WHERE "assigneeId" IS NOT NULL AND "assigneeId_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstanceStep.assigneeId has unmapped values'; END IF;
  IF EXISTS (SELECT 1 FROM "WorkflowInstanceStep" WHERE "decidedById" IS NOT NULL AND "decidedById_new" IS NULL) THEN RAISE EXCEPTION '0006: WorkflowInstanceStep.decidedById has unmapped values'; END IF;
END $$;

-- ══ E. Swap: drop legacy columns, promote numeric columns, enforce keys ═══
-- Organization
ALTER TABLE "Organization" DROP COLUMN "id";
ALTER TABLE "Organization" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "Organization" ADD PRIMARY KEY ("id");

-- User
ALTER TABLE "User" DROP COLUMN "id";
ALTER TABLE "User" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "User" ADD PRIMARY KEY ("id");
ALTER TABLE "User" DROP COLUMN "organizationId";
ALTER TABLE "User" RENAME COLUMN "organizationId_new" TO "organizationId";
ALTER TABLE "User" DROP COLUMN "managerId";
ALTER TABLE "User" RENAME COLUMN "managerId_new" TO "managerId";
ALTER TABLE "User" DROP COLUMN "departmentId";
ALTER TABLE "User" RENAME COLUMN "departmentId_new" TO "departmentId";
ALTER TABLE "User" DROP COLUMN "teamId";
ALTER TABLE "User" RENAME COLUMN "teamId_new" TO "teamId";

-- Department
ALTER TABLE "Department" DROP COLUMN "id";
ALTER TABLE "Department" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "Department" ADD PRIMARY KEY ("id");
ALTER TABLE "Department" DROP COLUMN "organizationId";
ALTER TABLE "Department" RENAME COLUMN "organizationId_new" TO "organizationId";
ALTER TABLE "Department" ADD CONSTRAINT "Department_organizationId_name_key" UNIQUE ("organizationId", "name");

-- Team
ALTER TABLE "Team" DROP COLUMN "id";
ALTER TABLE "Team" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "Team" ADD PRIMARY KEY ("id");
ALTER TABLE "Team" DROP COLUMN "departmentId";
ALTER TABLE "Team" RENAME COLUMN "departmentId_new" TO "departmentId";
ALTER TABLE "Team" ADD CONSTRAINT "Team_departmentId_name_key" UNIQUE ("departmentId", "name");

-- Counterparty
ALTER TABLE "Counterparty" DROP COLUMN "id";
ALTER TABLE "Counterparty" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "Counterparty" ADD PRIMARY KEY ("id");
ALTER TABLE "Counterparty" DROP COLUMN "organizationId";
ALTER TABLE "Counterparty" RENAME COLUMN "organizationId_new" TO "organizationId";
ALTER TABLE "Counterparty" ADD CONSTRAINT "Counterparty_name_organizationId_key" UNIQUE ("name", "organizationId");

-- CounterpartyContact
ALTER TABLE "CounterpartyContact" DROP COLUMN "id";
ALTER TABLE "CounterpartyContact" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "CounterpartyContact" ADD PRIMARY KEY ("id");
ALTER TABLE "CounterpartyContact" DROP COLUMN "counterpartyId";
ALTER TABLE "CounterpartyContact" RENAME COLUMN "counterpartyId_new" TO "counterpartyId";

-- UploadedFile
ALTER TABLE "UploadedFile" DROP COLUMN "id";
ALTER TABLE "UploadedFile" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "UploadedFile" ADD PRIMARY KEY ("id");

-- WorkflowRule
ALTER TABLE "WorkflowRule" DROP COLUMN "id";
ALTER TABLE "WorkflowRule" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "WorkflowRule" ADD PRIMARY KEY ("id");
ALTER TABLE "WorkflowRule" DROP COLUMN "organizationId";
ALTER TABLE "WorkflowRule" RENAME COLUMN "organizationId_new" TO "organizationId";

-- WorkflowRuleStep
ALTER TABLE "WorkflowRuleStep" DROP COLUMN "id";
ALTER TABLE "WorkflowRuleStep" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "WorkflowRuleStep" ADD PRIMARY KEY ("id");
ALTER TABLE "WorkflowRuleStep" DROP COLUMN "ruleId";
ALTER TABLE "WorkflowRuleStep" RENAME COLUMN "ruleId_new" TO "ruleId";
ALTER TABLE "WorkflowRuleStep" ADD CONSTRAINT "WorkflowRuleStep_ruleId_order_key" UNIQUE ("ruleId", "order");

-- DeclarationSnapshot / DeclarationDetail
ALTER TABLE "DeclarationSnapshot" DROP COLUMN "id";
ALTER TABLE "DeclarationSnapshot" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "DeclarationSnapshot" ADD PRIMARY KEY ("id");
ALTER TABLE "DeclarationSnapshot" DROP COLUMN "declarationId";
ALTER TABLE "DeclarationSnapshot" RENAME COLUMN "declarationPk_new" TO "declarationPk";
ALTER TABLE "DeclarationSnapshot" ADD CONSTRAINT "DeclarationSnapshot_declarationPk_key" UNIQUE ("declarationPk");

ALTER TABLE "DeclarationDetail" DROP COLUMN "id";
ALTER TABLE "DeclarationDetail" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "DeclarationDetail" ADD PRIMARY KEY ("id");
ALTER TABLE "DeclarationDetail" DROP COLUMN "declarationId";
ALTER TABLE "DeclarationDetail" RENAME COLUMN "declarationPk_new" TO "declarationPk";
ALTER TABLE "DeclarationDetail" ADD CONSTRAINT "DeclarationDetail_declarationPk_key" UNIQUE ("declarationPk");

-- DeclarationFile
ALTER TABLE "DeclarationFile" DROP COLUMN "id";
ALTER TABLE "DeclarationFile" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "DeclarationFile" ADD PRIMARY KEY ("id");
ALTER TABLE "DeclarationFile" DROP COLUMN "declarationId";
ALTER TABLE "DeclarationFile" RENAME COLUMN "declarationPk_new" TO "declarationPk";
ALTER TABLE "DeclarationFile" DROP COLUMN "fileId";
ALTER TABLE "DeclarationFile" RENAME COLUMN "fileId_new" TO "fileId";
ALTER TABLE "DeclarationFile" ADD CONSTRAINT "DeclarationFile_fileId_key" UNIQUE ("fileId");

-- Declaration FK columns (public text id and PK are untouched).
ALTER TABLE "Declaration" DROP COLUMN "organizationId";
ALTER TABLE "Declaration" RENAME COLUMN "organizationId_new" TO "organizationId";
ALTER TABLE "Declaration" DROP COLUMN "declarerUserId";
ALTER TABLE "Declaration" RENAME COLUMN "declarerUserId_new" TO "declarerUserId";
ALTER TABLE "Declaration" DROP COLUMN "currentApproverUserId";
ALTER TABLE "Declaration" RENAME COLUMN "currentApproverUserId_new" TO "currentApproverUserId";
ALTER TABLE "Declaration" DROP COLUMN "counterpartyId";
ALTER TABLE "Declaration" RENAME COLUMN "counterpartyId_new" TO "counterpartyId";

-- WorkflowInstance: numeric PK + numeric declaration reference.
ALTER TABLE "WorkflowInstance" DROP COLUMN "declarationId";
ALTER TABLE "WorkflowInstance" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "WorkflowInstance" ADD PRIMARY KEY ("id");
ALTER TABLE "WorkflowInstance" RENAME COLUMN "declarationPk_new" TO "declarationPk";
ALTER TABLE "WorkflowInstance" ADD CONSTRAINT "WorkflowInstance_declarationPk_key" UNIQUE ("declarationPk");
ALTER TABLE "WorkflowInstance" DROP COLUMN "ruleId";
ALTER TABLE "WorkflowInstance" RENAME COLUMN "ruleId_new" TO "ruleId";

-- WorkflowInstanceStep
ALTER TABLE "WorkflowInstanceStep" DROP COLUMN "id";
ALTER TABLE "WorkflowInstanceStep" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "WorkflowInstanceStep" ADD PRIMARY KEY ("id");
ALTER TABLE "WorkflowInstanceStep" DROP COLUMN "instanceId";
ALTER TABLE "WorkflowInstanceStep" RENAME COLUMN "instanceId_new" TO "instanceId";
ALTER TABLE "WorkflowInstanceStep" DROP COLUMN "declarationId";
ALTER TABLE "WorkflowInstanceStep" RENAME COLUMN "declarationPk_new" TO "declarationPk";
ALTER TABLE "WorkflowInstanceStep" DROP COLUMN "assigneeId";
ALTER TABLE "WorkflowInstanceStep" RENAME COLUMN "assigneeId_new" TO "assigneeId";
ALTER TABLE "WorkflowInstanceStep" DROP COLUMN "decidedById";
ALTER TABLE "WorkflowInstanceStep" RENAME COLUMN "decidedById_new" TO "decidedById";
ALTER TABLE "WorkflowInstanceStep" ADD CONSTRAINT "WorkflowInstanceStep_instanceId_stepOrder_key" UNIQUE ("instanceId", "stepOrder");

-- ══ E2. Enforce every relationship with an explicitly reviewed rule ════════
ALTER TABLE "User" ADD CONSTRAINT "User_manager_fk" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "User" ADD CONSTRAINT "User_organization_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT;
ALTER TABLE "User" ADD CONSTRAINT "User_department_fk" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL;
ALTER TABLE "User" ADD CONSTRAINT "User_team_fk" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL;
ALTER TABLE "Department" ADD CONSTRAINT "Department_organization_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Team" ADD CONSTRAINT "Team_department_fk" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE CASCADE;
ALTER TABLE "Counterparty" ADD CONSTRAINT "Counterparty_organization_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL;
ALTER TABLE "CounterpartyContact" ADD CONSTRAINT "CounterpartyContact_counterparty_fk" FOREIGN KEY ("counterpartyId") REFERENCES "Counterparty"("id") ON DELETE CASCADE;
ALTER TABLE "Declaration" ADD CONSTRAINT "Declaration_organization_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT;
ALTER TABLE "Declaration" ADD CONSTRAINT "Declaration_declarer_fk" FOREIGN KEY ("declarerUserId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Declaration" ADD CONSTRAINT "Declaration_approver_fk" FOREIGN KEY ("currentApproverUserId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Declaration" ADD CONSTRAINT "Declaration_counterparty_fk" FOREIGN KEY ("counterpartyId") REFERENCES "Counterparty"("id") ON DELETE SET NULL;
ALTER TABLE "DeclarationSnapshot" ADD CONSTRAINT "DeclarationSnapshot_declaration_fk" FOREIGN KEY ("declarationPk") REFERENCES "Declaration"("declarationPk") ON DELETE CASCADE;
ALTER TABLE "DeclarationDetail" ADD CONSTRAINT "DeclarationDetail_declaration_fk" FOREIGN KEY ("declarationPk") REFERENCES "Declaration"("declarationPk") ON DELETE CASCADE;
ALTER TABLE "DeclarationFile" ADD CONSTRAINT "DeclarationFile_declaration_fk" FOREIGN KEY ("declarationPk") REFERENCES "Declaration"("declarationPk") ON DELETE CASCADE;
ALTER TABLE "DeclarationFile" ADD CONSTRAINT "DeclarationFile_file_fk" FOREIGN KEY ("fileId") REFERENCES "UploadedFile"("id") ON DELETE CASCADE;
ALTER TABLE "WorkflowRule" ADD CONSTRAINT "WorkflowRule_organization_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL;
ALTER TABLE "WorkflowRuleStep" ADD CONSTRAINT "WorkflowRuleStep_rule_fk" FOREIGN KEY ("ruleId") REFERENCES "WorkflowRule"("id") ON DELETE CASCADE;
ALTER TABLE "WorkflowInstance" ADD CONSTRAINT "WorkflowInstance_declaration_fk" FOREIGN KEY ("declarationPk") REFERENCES "Declaration"("declarationPk") ON DELETE CASCADE;
ALTER TABLE "WorkflowInstance" ADD CONSTRAINT "WorkflowInstance_rule_fk" FOREIGN KEY ("ruleId") REFERENCES "WorkflowRule"("id") ON DELETE SET NULL;
ALTER TABLE "WorkflowInstanceStep" ADD CONSTRAINT "WorkflowInstanceStep_instance_fk" FOREIGN KEY ("instanceId") REFERENCES "WorkflowInstance"("id") ON DELETE CASCADE;
ALTER TABLE "WorkflowInstanceStep" ADD CONSTRAINT "WorkflowInstanceStep_declaration_fk" FOREIGN KEY ("declarationPk") REFERENCES "Declaration"("declarationPk") ON DELETE CASCADE;
ALTER TABLE "WorkflowInstanceStep" ADD CONSTRAINT "WorkflowInstanceStep_assignee_fk" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "WorkflowInstanceStep" ADD CONSTRAINT "WorkflowInstanceStep_decider_fk" FOREIGN KEY ("decidedById") REFERENCES "User"("id") ON DELETE SET NULL;

-- Scoped counterparty identity on the numeric keys (global NULL-org rows
-- remain exempt, as before).
CREATE UNIQUE INDEX IF NOT EXISTS "Counterparty_name_org_unique"
  ON "Counterparty"("name", "organizationId")
  WHERE "organizationId" IS NOT NULL;

-- ══ F. Reporting views on the numeric schema (migration-owned) ════════════
CREATE VIEW "v_declaration_status_summary" AS
  SELECT "organizationId" AS "organizationId", "status" AS "status",
         COUNT(*) AS "count", SUM("value") AS "totalValue"
  FROM "Declaration" GROUP BY "organizationId", "status";

CREATE VIEW "v_declarations_monthly" AS
  SELECT "organizationId" AS "organizationId",
         to_char("eventDate", 'YYYY-MM') AS "month",
         COUNT(*) AS "count",
         SUM(CASE WHEN "status" = 'Approved' THEN 1 ELSE 0 END) AS "approved",
         SUM(CASE WHEN "status" = 'Declined' THEN 1 ELSE 0 END) AS "declined",
         SUM("value") AS "totalValue"
  FROM "Declaration" WHERE "eventDate" IS NOT NULL
  GROUP BY "organizationId", to_char("eventDate", 'YYYY-MM');

CREATE VIEW "v_declaration_type_breakdown" AS
  SELECT "organizationId" AS "organizationId", "type" AS "type",
         COUNT(*) AS "count", SUM("value") AS "totalValue"
  FROM "Declaration" GROUP BY "organizationId", "type";

CREATE VIEW "v_workflow_current_step" AS
  SELECT "declarationPk", "stepOrder", "role", "assigneeId", "assigneeName", "status"
  FROM "WorkflowInstanceStep" WHERE "status" = 'pending';

CREATE VIEW "v_workflow_step_sla" AS
  SELECT s."role" AS "role", s."decidedAt" AS "decidedAt",
         d."eventDate" AS "eventDate"
  FROM "WorkflowInstanceStep" s JOIN "Declaration" d ON d."declarationPk" = s."declarationPk"
  WHERE s."decidedAt" IS NOT NULL;

CREATE VIEW "v_counterparty_concentration" AS
  SELECT d."organizationId" AS "organizationId",
         COALESCE(c."name", 'Unknown') AS "counterparty",
         COUNT(*) AS "count", SUM(d."value") AS "totalValue",
         AVG(d."value") AS "avgValue"
  FROM "Declaration" d LEFT JOIN "Counterparty" c ON c."id" = d."counterpartyId"
  GROUP BY d."organizationId", COALESCE(c."name", 'Unknown');

CREATE VIEW "v_high_value_declarations" AS
  SELECT d."id" AS "id", s."declarerName" AS "employee",
         s."managerDisplayName" AS "lineManager", s."department" AS "department",
         d."type" AS "type", COALESCE(c."name", 'Unknown') AS "counterparty",
         d."value" AS "value", d."eventDate" AS "date", d."status" AS "status",
         d."organizationId" AS "organizationId"
  FROM "Declaration" d
  LEFT JOIN "DeclarationSnapshot" s ON s."declarationPk" = d."declarationPk"
  LEFT JOIN "Counterparty" c ON c."id" = d."counterpartyId";
